# Build and test on each commit. Create a release on tagged commits.
#
# Binaries on each platform are stripped. This removes debug symbols.
name: Build
on: [push,  pull_request_target]

jobs:
  build-all:
    name: ${{ matrix.os-name }}-build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:
          - os: ubuntu-latest
            os-name: Linux
            container: fossa/haskell-static-alpine:ghc-8.10.4
            project-file: cabal.project.ci.linux
            ghc: '8.10.5'

          - os: macos-latest
            os-name: macOS
            project-file: cabal.project.ci.macos
            ghc: '8.10.4'

          - os: windows-latest
            os-name: Windows
            project-file: cabal.project.ci.windows
            ghc: '8.10.5'

    steps:
    - uses: actions/checkout@v2

    # Install tools used in `vendor_download.sh`.
    - name: Install alpine binary dependencies
      if: ${{ contains(matrix.os, 'ubuntu') }}
      shell: sh
      run: |
        apk add bash xz-dev bzip2-dev bzip2-static upx curl jq

    - name: Install MacOS binary dependencies
      if: ${{ contains(matrix.os, 'macos') }}
      run: |
        brew install upx jq

    # Set up Haskell.
    - uses: haskell/actions/setup@v1
      id: setup-haskell
      name: Setup ghc/cabal (non-alpine)
      if: ${{ !contains(matrix.os, 'ubuntu') }}
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Debugging information
      run: |
        ghc --version || echo "no ghc"
        cabal --version || echo "no cabal"
        ghcup --version || echo "no ghcup"

    # Build Spectrometer.
    - uses: actions/cache@v2
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store || '~/.cabal/store' }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-cache-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-cabal-cache-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Update vendored binaries
      run: |
        mkdir vendor
        ./vendor_download.sh
      env:
        GITHUB_TOKEN: ${{ secrets.BASIS_ACCESS_TOKEN }}

    - name: Build
      # Occasionally, we run out of memory on the build process.
      # Since cabal uses incremental compilation, we can retry from where we left off
      #   by simply re-running cabal if we fail.
      env:
        RUN_CMD: cabal build --project-file=${{ matrix.project-file }} all
      run: |
        cabal update
        $RUN_CMD || $RUN_CMD

    - name: Run tests
      run: |
        cabal test --project-file=${{ matrix.project-file }} all

    # Save artifacts.
    - name: Find and move binaries (Windows)
      if: ${{ contains(matrix.os, 'windows') }}
      run: |
        mkdir release
        find . -type f -path '*/fossa/fossa.exe' -exec cp {} release \;
        find . -type f -path '*/pathfinder/pathfinder.exe' -exec cp {} release \;

    - name: Find and move binaries (non-Windows)
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        mkdir release
        find . -type f -path '*/fossa/fossa' -exec cp {} release \;
        find . -type f -path '*/pathfinder/pathfinder' -exec cp {} release \;

    - name: Strip binaries
      run: |
        strip release/*

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-binaries
        path: release

  # Run linter and format checkers independently, so you see errors from both.
  linter-check:
    name: linter-check
    runs-on: ubuntu-latest
    container: ghcr.io/fossas/haskell-dev-tools:8.10.4

    steps:
    - uses: actions/checkout@v2

    - name: Run hlint
      run: |
        make lint

  format-check:
    name: formatter-check
    runs-on: ubuntu-latest
    container: ghcr.io/fossas/haskell-dev-tools:8.10.4

    steps:
    - uses: actions/checkout@v2

    # Run the formatter
    - name: run fourmolu
      run: |
        make fmt

    # If git has changes, then the formatter check fails.
    - name: check git status
      run: |
        git diff --exit-code

  create-release:
    name: create-release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: ['build-all']

    steps:
    - uses: actions/download-artifact@v2

    - name: Get version
      id: get-version
      # This strips the 'v' prefix from the tag.
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    # This uses names compatible with our install script.
    - name: Bundle binaries
      run: |
        mkdir release

        ls -R

        chmod +x Linux-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_linux_amd64.zip Linux-binaries/fossa
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_linux_amd64.zip Linux-binaries/pathfinder

        chmod +x macOS-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_darwin_amd64.zip macOS-binaries/fossa
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_darwin_amd64.zip macOS-binaries/pathfinder

        chmod +x Windows-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_windows_amd64.zip Windows-binaries/fossa.exe
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_windows_amd64.zip Windows-binaries/pathfinder.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
