# Build, test, and (sometimes) create a release
#
# Linux builds are done under our haskell-static-alpine image (see: fossas/haskell-static-alpine)
# macOS/windows builds use github's setup-haskell action
#
# Binaries on each platform are stripped. This removes debug symbols.
name: Build
on: push

jobs:

  build-all:
    name: ${{ matrix.os-name }}-build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    defaults:
      run:
        shell: bash

    strategy:
      # TODO: remove me
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:

          - os: ubuntu-latest
            os-name: Linux
            container: quay.io/fossa/haskell-static-alpine:ghc-8.10
            project-file: cabal.project.ci.linux
            # note: the real version is the one bundled in the docker image
            ghc: '8.10'

          - os: macos-latest
            os-name: macOS
            project-file: cabal.project.ci.macos
            ghc: '8.10.1'

          - os: windows-latest
            os-name: Windows
            project-file: cabal.project.ci.windows
            ghc: '8.10.1'

    steps:
    - uses: actions/checkout@v2

    - name: Install alpine binary dependencies
      if: ${{ contains(matrix.os, 'ubuntu') }}
      shell: sh
      run: |
        apk add bash xz-dev bzip2-dev bzip2-static upx curl jq

    - name: Install MacOS binary dependencies
      if: ${{ contains(matrix.os, 'macos') }}
      run: |
        brew install upx jq

    - uses: actions/setup-haskell@v1.1
      id: setup-haskell
      name: Setup ghc/cabal (non-alpine)
      if: ${{ !contains(matrix.os, 'ubuntu') }}
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v1
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store || '~/.cabal/store' }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-cache-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-cabal-cache-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Build
      run: |
        mkdir vendor
        touch vendor/nomossa
        touch vendor/pathfinder
        touch vendor/sherlock-cli
        touch vendor/ramjet-cli-ipr
        cabal update
        cabal build --project-file=${{ matrix.project-file }} all

    - name: Run tests
      run: |
        cabal test --project-file=${{ matrix.project-file }} all

    - name: Find and move binaries (windows)
      if: ${{ contains(matrix.os, 'windows') }}
      run: |
        mkdir release
        find . -type f -path '*/fossa/fossa.exe' -exec cp {} release \;
        find . -type f -path '*/pathfinder/pathfinder.exe' -exec cp {} release \;
  
    - name: Find and move binaries (non-windows)
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        mkdir release
        find . -type f -path '*/fossa/fossa' -exec cp {} release \;
        find . -type f -path '*/pathfinder/pathfinder' -exec cp {} release \;

    - name: Update vendored binaries
      if: ${{ !contains(matrix.os, 'windows') }}
      run: ./vendor_download.sh
      env:
        GITHUB_TOKEN: ${{ secrets.BASIS_ACCESS_TOKEN }}

    - name: Rebuild with new vendored binaries
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        echo '' >> src/App/VPSScan/EmbeddedBinary.hs
        cabal build --project-file=${{ matrix.project-file }} all

    - name: Find and move vpscli
      if: ${{ !contains(matrix.os, 'windows') }}
      run: |
        find . -type f -path '*/vpscli/vpscli' -exec mv {} release \;
        ls -lh release/

    - name: Strip binaries
      run: |
        strip release/*

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-binaries
        path: release

  create-release:
    name: create-release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: ['build-all']

    steps:
    - uses: actions/download-artifact@v2

    - name: Get version
      id: get-version
      # note that this strips the 'v' prefix from the tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    # This uses names compatible with our install script
    - name: Bundle binaries
      run: |
        mkdir release

        ls -R

        chmod +x Linux-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_linux_amd64.zip Linux-binaries/fossa
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_linux_amd64.zip Linux-binaries/pathfinder
        zip -j release/vpscli_${{ steps.get-version.outputs.VERSION }}_linux_amd64.zip Linux-binaries/vpscli

        chmod +x macOS-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_darwin_amd64.zip macOS-binaries/fossa
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_darwin_amd64.zip macOS-binaries/pathfinder
        zip -j release/vpscli_${{ steps.get-version.outputs.VERSION }}_darwin_amd64.zip macOS-binaries/vpscli

        chmod +x Windows-binaries/*
        zip -j release/fossa_${{ steps.get-version.outputs.VERSION }}_windows_amd64.zip Windows-binaries/fossa.exe
        zip -j release/pathfinder_${{ steps.get-version.outputs.VERSION }}_windows_amd64.zip Windows-binaries/pathfinder.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
