name: Dependency scan
on: push

jobs:
  dependency-scan:
    name: dependency-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debugging information
        run: |
          ghc --version || echo "no ghc"
          cabal --version || echo "no cabal"
          ghcup --version || echo "no ghcup"

      # Ignore for CI testing
      # - name: Update cabal cache for spectrometer run
      #   run: |
      #     cabal update

      - name: Install spectrometer from github
        run: |
          BINDIR=$GITHUB_WORKSPACE env | sort
          false
          
        # BINDIR=$GITHUB_WORKSPACE curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | bash

      - name: Use Spectrometer's GHC and Cabal
        run: |
          ghcup install ghc 8.10.4
          ghcup set ghc 8.10.4
          ghcup install cabal 3.4.0.0
          ghcup set cabal 3.4.0.0

      - name: Run dependency scan on Spectrometer
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          $GITHUB_WORKSPACE/fossa analyze --filter cabal@.

      - name: Check for scan results
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          fossa test
