name: Dependency scan
on: push

jobs:
  dependency-scan:
    name: dependency-scan
    runs-on: ubuntu-latest

    steps:
      - name: Install spectrometer from github
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | bash

      - name: Run dependency scan
        env:
          FOSSA_API_TOKEN: ${{ secrets.FOSSA_API_TOKEN }}
        run: |
          fossa analyze --filter cabal@.
